data:
  AzureWebJobsStorage: RGVmYXVsdEVuZHBvaW50c1Byb3RvY29sPWh0dHBzO0FjY291bnROYW1lPW5laWdoYm9ybHlzdG9yYWdlYWNjb3VudDtBY2NvdW50S2V5PWYrOXdVWWowbW1JTFdDKytlZWVKNGtzanRiK0V1WXdKNGo1bDFHUVZHUE9KcTVtcnVuWjZDN0dvOHhzdDZ2b2hubjQrQU92L0dxUmErQVN0VWl3d2hRPT07RW5kcG9pbnRTdWZmaXg9Y29yZS53aW5kb3dzLm5ldA==
  FUNCTIONS_WORKER_RUNTIME: cHl0aG9u
  FUNCTIONS_EXTENSION_VERSION: fjQ=
  WEBSITE_CONTENTAZUREFILECONNECTIONSTRING: RGVmYXVsdEVuZHBvaW50c1Byb3RvY29sPWh0dHBzO0FjY291bnROYW1lPW5laWdoYm9ybHlzdG9yYWdlYWNjb3VudDtBY2NvdW50S2V5PWYrOXdVWWowbW1JTFdDKytlZWVKNGtzanRiK0V1WXdKNGo1bDFHUVZHUE9KcTVtcnVuWjZDN0dvOHhzdDZ2b2hubjQrQU92L0dxUmErQVN0VWl3d2hRPT07RW5kcG9pbnRTdWZmaXg9Y29yZS53aW5kb3dzLm5ldA==
  WEBSITE_CONTENTSHARE: bmVpZ2hib3JseW5nb2NoYWliODUw
  MyDbConnection: bW9uZ29kYjovL25laWdoYm9ybHljb3Ntb3NkYjo0Q2F2d1dCOVZEWElQZ2tvVjQyWWQxclF1RnlERDR5ODRZU0FUNWdpS0JuMk44UEZROXU4b0JiSGRJWnVicXowNzdGSGU1VGtrVTFOQUNEYkxvYktaZz09QG5laWdoYm9ybHljb3Ntb3NkYi5tb25nby5jb3Ntb3MuYXp1cmUuY29tOjEwMjU1Lz9zc2w9dHJ1ZSZyZXBsaWNhU2V0PWdsb2JhbGRiJnJldHJ5d3JpdGVzPWZhbHNlJm1heElkbGVUaW1lTVM9MTIwMDAwJmFwcE5hbWU9QG5laWdoYm9ybHljb3Ntb3NkYkA=
apiVersion: v1
kind: Secret
metadata:
  name: neighborcluster
---
data:
  host.master: U0gyNUpzTE9xaU9KWFRmVmg4UWxEWmU2S3JqYV9oWjlkRGp3a2tRdDBoOFZBekZ1Z3BhSkpBPT0=
  host.function.default: N1BMelRsZFJuLUp1RVVGajB5Ym1kUjllclBqR3ZHckJCVXhhWGlOTjZaQnRBekZ1dGFsemFRPT0=
  host.systemKey.default: VTllbXg0Zzc2clBGT1cxR0pjb196OF9yam5YTnNJR1M3VFlJZ0F6TWNwNFNBekZ1eXRVUi1RPT0=
  functions.createadvertisement.default: QkFmQ1Y4c0JMVEh0djdrNGZ4QzBNZU04dEdQdFU5NlFROTd4cWlBN0MzQ0VBekZ1YzBhSERRPT0=
  functions.deleteadvertisement.default: cVFqZEd2VEFRdnY0amlGUGdpNFZFcFQtaTJGOEJOY0RmR0Qyd1N2eWxpRENBekZ1Sk81OHBRPT0=
  functions.getadvertisement.default: WnJhWHlFQVlXX0tBY1g4eEg2SGM1VWRLRExTbUtRZ0pIdUtiWmNIaEtIanRBekZ1aEM0OEhBPT0=
  functions.getadvertisements.default: QkFQUWwxSTJKTEpRZXFlbi13MWl3U0lNWUZUeTRhbXVlOEZnNkRaVHlOWkxBekZ1UkUyTDJRPT0=
  functions.getpost.default: SHdwdU1WLXhxT0lSQUpOV3ZWbk5iWERWSjNieHE4Y1Q5RFVIdGplRWJHdmhBekZ1aFV3X0xRPT0=
  functions.getposts.default: cVB5VHRsbW9TWUhxYXRwazMyZmptTzBkc1lrME5YZkdlQVo0bXZKY1l2WjFBekZ1c1UxME13PT0=
  functions.updateadvertisement.default: Y1Ezc3kzelQzOWJ3VjU4bnozNld5WnlCR0pNbEZoRGhBMHFYQjJDc1ctQ3lBekZ1dmdncVhnPT0=
apiVersion: v1
kind: Secret
metadata:
  name: func-keys-kube-secret-neighborcluster
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: neighborcluster-function-keys-identity-svc-act
---
rules:
- apiGroups:
  - ''
  resources:
  - secrets
  - configMaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: functions-keys-manager-role
---
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: functions-keys-manager-role
subjects:
- kind: ServiceAccount
  name: neighborcluster-function-keys-identity-svc-act
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: neighborcluster-function-keys-identity-svc-act-functions-keys-manager-rolebinding
---
apiVersion: v1
kind: Service
metadata:
  name: neighborcluster-http
spec:
  selector:
    app: neighborcluster-http
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: neighborcluster-http
  labels:
    app: neighborcluster-http
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neighborcluster-http
  template:
    metadata:
      labels:
        app: neighborcluster-http
    spec:
      containers:
      - name: neighborcluster-http
        image: neighborlyregistry.azurecr.io/neighborly-api
        ports:
        - containerPort: 80
        env:
        - name: AzureFunctionsJobHost__functions__0
          value: createAdvertisement
        - name: AzureFunctionsJobHost__functions__1
          value: deleteAdvertisement
        - name: AzureFunctionsJobHost__functions__2
          value: getAdvertisement
        - name: AzureFunctionsJobHost__functions__3
          value: getAdvertisements
        - name: AzureFunctionsJobHost__functions__4
          value: getPost
        - name: AzureFunctionsJobHost__functions__5
          value: getPosts
        - name: AzureFunctionsJobHost__functions__6
          value: updateAdvertisement
        - name: AzureWebJobsSecretStorageType
          value: kubernetes
        - name: AzureWebJobsKubernetesSecretName
          value: secrets/func-keys-kube-secret-neighborcluster
        envFrom:
        - secretRef:
            name: neighborcluster
        readinessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 240
          httpGet:
            path: /
            port: 80
            scheme: HTTP
        startupProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 240
          httpGet:
            path: /
            port: 80
            scheme: HTTP
      serviceAccountName: neighborcluster-function-keys-identity-svc-act
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: neighborcluster
  labels:
    app: neighborcluster
spec:
  selector:
    matchLabels:
      app: neighborcluster
  template:
    metadata:
      labels:
        app: neighborcluster
    spec:
      containers:
      - name: neighborcluster
        image: neighborlyregistry.azurecr.io/neighborly-api
        env:
        - name: AzureFunctionsJobHost__functions__0
          value: eventHubTrigger
        envFrom:
        - secretRef:
            name: neighborcluster
        readinessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 240
          httpGet:
            path: /
            port: 80
            scheme: HTTP
        startupProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 240
          httpGet:
            path: /
            port: 80
            scheme: HTTP
      serviceAccountName: neighborcluster-function-keys-identity-svc-act
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: neighborcluster
  labels: {}
spec:
  scaleTargetRef:
    name: neighborcluster
  triggers:
  - type: eventgridtrigger
    metadata:
      direction: in
      eventHubName: testhub
      connection: Endpoint=sb://udacityneighborly.servicebus.windows.net/;SharedAccessKeyName=allpolicy;SharedAccessKey=LOxUOkN13xN038T1VoSsmaTt4s7vq/+VCzduS5/nH9A=;EntityPath=testhub
---

